### ISSUE TITLE
denormalize?

### ISSUE THREAD

**Issue by rpinna** [monojack/graphql-normalizr#37]
We currently use the normalizr package from which you shamelessly piggybacked :)

We use the denormalize call for certain selector operations. Are there plans to implement that and/or a suggested alternative?

**Comment by monojack** [comment]
Hey, @rpinna, that's a really good question. There isn't a way to denormalize without "polluting" the data, because it would require the schema and all the options you configured when instantiating the `normalizer` (`new GraphQLNormalizr(options)`).

There are currently 2 ways to go about it

1. Keep the `normalizer` instance around, somewhere (you could have a module for the normalizers just like you have for selectors, reducers etc.), and enable the [`typenames`](https://github.com/monojack/graphql-normalizr#typenames) option. This way you would be able to figure out where every id points to after a lot of filtering, mapping and finding. Goes without saying that I wouldn't suggest this approach.
2. Enable the [`typePointers`](https://github.com/monojack/graphql-normalizr#typepointers) option and then it would be really easy to implement a `denormalize` method yourself. The trade-off here is that all your ids will now be objects  (previously strings) that have a property `.collection` which tells you where to look for the data.
